version: '3.8'
services:
  app:
    build:
      context: .
    working_dir: /app
    volumes:
      - $PWD:./
      - /node_modules
    command: npm run dev
  test:
    build: 
      context: .
      dockerfile: ./DockerfileTest
    working_dir: /app
    volumes:
      - $PWD:./
      - /node_modules
    depends_on:
      - app
    entrypoint: npm